spring.application.name=production_Ready

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.datasource.url=jdbc:postgresql://localhost:5432/production
spring.datasource.username=postgres
spring.datasource.password=root

server.port=9000
employeeservice.base.url=http://localhost:8080

logging.level.com.week4.production_Ready.clients.Implimentation= DEBUG
#logging.level.root=TRACE
logging.pattern.console=%d{dd-mm-yyyy hh:mm:ss} [%c{2.}] ---%m%n

#file configuration logging
logging.file.name=application.log
logging.config=classpath:logback-spring.xml


#Actuator Configuration
management.endpoints.web.exposure.include=*

management.info.env.enabled=true
info.TheK=Good
